export type CuratedFoodSeed = {
  name: string;
  aliases: string[];
  servingSize: number;
  servingUnit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  imageUrl?: string;
};

export const curatedFoods: CuratedFoodSeed[] = [
  { name: "Yumurta", aliases: ["egg"], servingSize: 100, servingUnit: "g", calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, sugar: 1.1 },
  { name: "Haşlanmış Yumurta", aliases: ["haslanmis yumurta", "boiled egg"], servingSize: 100, servingUnit: "g", calories: 155, protein: 13, carbs: 1.1, fat: 11, fiber: 0, sugar: 1.1 },
  { name: "Beyaz Peynir", aliases: ["peynir", "feta"], servingSize: 100, servingUnit: "g", calories: 264, protein: 14, carbs: 4.1, fat: 21, fiber: 0, sugar: 0.5 },
  { name: "Kaşar Peyniri", aliases: ["kasar peyniri", "cheddar"], servingSize: 100, servingUnit: "g", calories: 353, protein: 25, carbs: 2, fat: 27, fiber: 0, sugar: 0.5 },
  { name: "Lor Peyniri", aliases: ["lor", "cottage cheese"], servingSize: 100, servingUnit: "g", calories: 98, protein: 11, carbs: 3.4, fat: 4.3, fiber: 0, sugar: 2.7 },
  { name: "Siyah Zeytin", aliases: ["black olives"], servingSize: 100, servingUnit: "g", calories: 115, protein: 0.8, carbs: 6, fat: 10.7, fiber: 3.2, sugar: 0 },
  { name: "Yeşil Zeytin", aliases: ["yesil zeytin", "green olives"], servingSize: 100, servingUnit: "g", calories: 145, protein: 1, carbs: 3.8, fat: 15.3, fiber: 3.3, sugar: 0.5 },
  { name: "Domates", aliases: ["tomato"], servingSize: 100, servingUnit: "g", calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sugar: 2.6 },
  { name: "Salatalık", aliases: ["salatalik", "cucumber"], servingSize: 100, servingUnit: "g", calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7 },
  { name: "Ekmek", aliases: ["bread"], servingSize: 100, servingUnit: "g", calories: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, sugar: 5 },
  { name: "Tam Buğday Ekmeği", aliases: ["tam bugday ekmegi", "whole wheat bread"], servingSize: 100, servingUnit: "g", calories: 247, protein: 13, carbs: 41, fat: 4.2, fiber: 7, sugar: 6 },
  { name: "Yulaf", aliases: ["oats"], servingSize: 100, servingUnit: "g", calories: 389, protein: 16.9, carbs: 66, fat: 6.9, fiber: 10.6, sugar: 0.9 },
  { name: "Süt", aliases: ["sut", "milk"], servingSize: 100, servingUnit: "ml", calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sugar: 5.1 },
  { name: "Yoğurt", aliases: ["yogurt"], servingSize: 100, servingUnit: "g", calories: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, sugar: 4.7 },
  { name: "Bal", aliases: ["honey"], servingSize: 100, servingUnit: "g", calories: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0.2, sugar: 82 },
  { name: "Reçel", aliases: ["recel", "jam"], servingSize: 100, servingUnit: "g", calories: 278, protein: 0.4, carbs: 69, fat: 0.1, fiber: 1, sugar: 48 },
  { name: "Tereyağı", aliases: ["tereyagi", "butter"], servingSize: 100, servingUnit: "g", calories: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, sugar: 0.1 },
  { name: "Fıstık Ezmesi", aliases: ["fistik ezmesi", "peanut butter"], servingSize: 100, servingUnit: "g", calories: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, sugar: 9 },
  { name: "Tavuk Göğsü", aliases: ["tavuk", "chicken breast"], servingSize: 100, servingUnit: "g", calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0 },
  { name: "Tavuk But", aliases: ["chicken thigh"], servingSize: 100, servingUnit: "g", calories: 209, protein: 26, carbs: 0, fat: 10.9, fiber: 0, sugar: 0 },
  { name: "Hindi Göğsü", aliases: ["hindi", "turkey breast"], servingSize: 100, servingUnit: "g", calories: 135, protein: 30, carbs: 0, fat: 1, fiber: 0, sugar: 0 },
  { name: "Dana Eti", aliases: ["beef"], servingSize: 100, servingUnit: "g", calories: 250, protein: 26, carbs: 0, fat: 15, fiber: 0, sugar: 0 },
  { name: "Kıyma", aliases: ["kiyma", "ground beef"], servingSize: 100, servingUnit: "g", calories: 254, protein: 17, carbs: 0, fat: 20, fiber: 0, sugar: 0 },
  { name: "Somon", aliases: ["salmon"], servingSize: 100, servingUnit: "g", calories: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, sugar: 0 },
  { name: "Ton Balığı", aliases: ["ton baligi", "tuna"], servingSize: 100, servingUnit: "g", calories: 132, protein: 28, carbs: 0, fat: 1.3, fiber: 0, sugar: 0 },
  { name: "Levrek", aliases: ["sea bass"], servingSize: 100, servingUnit: "g", calories: 124, protein: 23, carbs: 0, fat: 2.6, fiber: 0, sugar: 0 },
  { name: "Çipura", aliases: ["cipura", "sea bream"], servingSize: 100, servingUnit: "g", calories: 128, protein: 21, carbs: 0, fat: 4, fiber: 0, sugar: 0 },
  { name: "Yumurta Beyazı", aliases: ["yumurta beyazi", "egg white"], servingSize: 100, servingUnit: "g", calories: 52, protein: 11, carbs: 0.7, fat: 0.2, fiber: 0, sugar: 0.7 },
  { name: "Mercimek", aliases: ["lentils"], servingSize: 100, servingUnit: "g", calories: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 7.9, sugar: 1.8 },
  { name: "Nohut", aliases: ["chickpeas"], servingSize: 100, servingUnit: "g", calories: 164, protein: 8.9, carbs: 27, fat: 2.6, fiber: 7.6, sugar: 4.8 },
  { name: "Kuru Fasulye", aliases: ["beans"], servingSize: 100, servingUnit: "g", calories: 127, protein: 8.7, carbs: 23, fat: 0.5, fiber: 6.4, sugar: 0.3 },
  { name: "Pirinç Pilavı", aliases: ["pirinc pilavi", "pilav", "rice"], servingSize: 100, servingUnit: "g", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, sugar: 0.1 },
  { name: "Bulgur Pilavı", aliases: ["bulgur pilavi", "bulgur"], servingSize: 100, servingUnit: "g", calories: 83, protein: 3.1, carbs: 18.6, fat: 0.2, fiber: 4.5, sugar: 0.1 },
  { name: "Makarna", aliases: ["pasta"], servingSize: 100, servingUnit: "g", calories: 158, protein: 5.8, carbs: 31, fat: 0.9, fiber: 1.8, sugar: 0.6 },
  { name: "Patates", aliases: ["potato"], servingSize: 100, servingUnit: "g", calories: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 2.2, sugar: 0.8 },
  { name: "Haşlanmış Patates", aliases: ["haslanmis patates", "boiled potato"], servingSize: 100, servingUnit: "g", calories: 87, protein: 1.9, carbs: 20, fat: 0.1, fiber: 1.8, sugar: 0.9 },
  { name: "Tatlı Patates", aliases: ["tatli patates", "sweet potato"], servingSize: 100, servingUnit: "g", calories: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, sugar: 4.2 },
  { name: "Erişte", aliases: ["eriste", "noodle"], servingSize: 100, servingUnit: "g", calories: 138, protein: 4.5, carbs: 25, fat: 2.1, fiber: 1.2, sugar: 0.4 },
  { name: "Lavaş", aliases: ["lavas", "lavash"], servingSize: 100, servingUnit: "g", calories: 275, protein: 9, carbs: 56, fat: 1.2, fiber: 2.2, sugar: 2.5 },
  { name: "Tortilla", aliases: ["wrap"], servingSize: 100, servingUnit: "g", calories: 312, protein: 8.2, carbs: 52, fat: 8, fiber: 3.1, sugar: 2.1 },
  { name: "Mısır", aliases: ["misir", "corn"], servingSize: 100, servingUnit: "g", calories: 96, protein: 3.4, carbs: 21, fat: 1.5, fiber: 2.4, sugar: 4.5 },
  { name: "Karabuğday", aliases: ["karabugday", "buckwheat"], servingSize: 100, servingUnit: "g", calories: 343, protein: 13.3, carbs: 71.5, fat: 3.4, fiber: 10, sugar: 0 },
  { name: "Kinoa", aliases: ["quinoa"], servingSize: 100, servingUnit: "g", calories: 120, protein: 4.4, carbs: 21.3, fat: 1.9, fiber: 2.8, sugar: 0.9 },
  { name: "Marul", aliases: ["lettuce"], servingSize: 100, servingUnit: "g", calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2, fiber: 1.3, sugar: 0.8 },
  { name: "Roka", aliases: ["arugula"], servingSize: 100, servingUnit: "g", calories: 25, protein: 2.6, carbs: 3.7, fat: 0.7, fiber: 1.6, sugar: 2.1 },
  { name: "Ispanak", aliases: ["spinach"], servingSize: 100, servingUnit: "g", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4 },
  { name: "Brokoli", aliases: ["broccoli"], servingSize: 100, servingUnit: "g", calories: 34, protein: 2.8, carbs: 6.6, fat: 0.4, fiber: 2.6, sugar: 1.7 },
  { name: "Kabak", aliases: ["zucchini"], servingSize: 100, servingUnit: "g", calories: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, sugar: 2.5 },
  { name: "Havuç", aliases: ["havuc", "carrot"], servingSize: 100, servingUnit: "g", calories: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 4.7 },
  { name: "Soğan", aliases: ["sogan", "onion"], servingSize: 100, servingUnit: "g", calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, sugar: 4.2 },
  { name: "Biber", aliases: ["pepper"], servingSize: 100, servingUnit: "g", calories: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, sugar: 4.2 },
  { name: "Mantar", aliases: ["mushroom"], servingSize: 100, servingUnit: "g", calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, sugar: 2 },
  { name: "Karnabahar", aliases: ["cauliflower"], servingSize: 100, servingUnit: "g", calories: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2, sugar: 1.9 },
  { name: "Lahana", aliases: ["cabbage"], servingSize: 100, servingUnit: "g", calories: 25, protein: 1.3, carbs: 5.8, fat: 0.1, fiber: 2.5, sugar: 3.2 },
  { name: "Elma", aliases: ["apple"], servingSize: 100, servingUnit: "g", calories: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, sugar: 10 },
  { name: "Muz", aliases: ["banana"], servingSize: 100, servingUnit: "g", calories: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sugar: 12 },
  { name: "Portakal", aliases: ["orange"], servingSize: 100, servingUnit: "g", calories: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, sugar: 9.4 },
  { name: "Mandalina", aliases: ["tangerine"], servingSize: 100, servingUnit: "g", calories: 53, protein: 0.8, carbs: 13, fat: 0.3, fiber: 1.8, sugar: 10.6 },
  { name: "Çilek", aliases: ["cilek", "strawberry"], servingSize: 100, servingUnit: "g", calories: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, sugar: 4.9 },
  { name: "Üzüm", aliases: ["uzum", "grape"], servingSize: 100, servingUnit: "g", calories: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9, sugar: 15.5 },
  { name: "Karpuz", aliases: ["watermelon"], servingSize: 100, servingUnit: "g", calories: 30, protein: 0.6, carbs: 7.6, fat: 0.2, fiber: 0.4, sugar: 6.2 },
  { name: "Kavun", aliases: ["melon"], servingSize: 100, servingUnit: "g", calories: 34, protein: 0.8, carbs: 8.2, fat: 0.2, fiber: 0.9, sugar: 7.9 },
  { name: "Armut", aliases: ["pear"], servingSize: 100, servingUnit: "g", calories: 57, protein: 0.4, carbs: 15, fat: 0.1, fiber: 3.1, sugar: 9.8 },
  { name: "Şeftali", aliases: ["seftali", "peach"], servingSize: 100, servingUnit: "g", calories: 39, protein: 0.9, carbs: 9.5, fat: 0.3, fiber: 1.5, sugar: 8.4 },
  { name: "Avokado", aliases: ["avocado"], servingSize: 100, servingUnit: "g", calories: 160, protein: 2, carbs: 8.5, fat: 14.7, fiber: 6.7, sugar: 0.7 },
  { name: "Badem", aliases: ["almond"], servingSize: 100, servingUnit: "g", calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12.5, sugar: 4.4 },
  { name: "Ceviz", aliases: ["walnut"], servingSize: 100, servingUnit: "g", calories: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7, sugar: 2.6 },
  { name: "Fındık", aliases: ["findik", "hazelnut"], servingSize: 100, servingUnit: "g", calories: 628, protein: 15, carbs: 17, fat: 61, fiber: 9.7, sugar: 4.3 },
  { name: "Antep Fıstığı", aliases: ["antep fistigi", "pistachio"], servingSize: 100, servingUnit: "g", calories: 560, protein: 20, carbs: 28, fat: 45, fiber: 10.6, sugar: 7.7 },
  { name: "Leblebi", aliases: ["roasted chickpeas"], servingSize: 100, servingUnit: "g", calories: 378, protein: 20, carbs: 63, fat: 6, fiber: 17, sugar: 10 },
  { name: "Hurma", aliases: ["date"], servingSize: 100, servingUnit: "g", calories: 282, protein: 2.5, carbs: 75, fat: 0.4, fiber: 8, sugar: 63 },
  { name: "Kuru Üzüm", aliases: ["kuru uzum", "raisin"], servingSize: 100, servingUnit: "g", calories: 299, protein: 3.1, carbs: 79, fat: 0.5, fiber: 3.7, sugar: 59 },
  { name: "Tavuk Döner", aliases: ["tavuk doner"], servingSize: 100, servingUnit: "g", calories: 215, protein: 18, carbs: 5, fat: 13, fiber: 0.8, sugar: 1 },
  { name: "Et Döner", aliases: ["et doner"], servingSize: 100, servingUnit: "g", calories: 250, protein: 20, carbs: 3, fat: 18, fiber: 0.5, sugar: 0.5 },
  { name: "Izgara Tavuk", aliases: ["grilled chicken"], servingSize: 100, servingUnit: "g", calories: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0 },
  { name: "Izgara Köfte", aliases: ["izgara kofte"], servingSize: 100, servingUnit: "g", calories: 240, protein: 18, carbs: 4, fat: 17, fiber: 0.5, sugar: 0.8 },
  { name: "Menemen", aliases: ["menemen"], servingSize: 100, servingUnit: "g", calories: 105, protein: 5, carbs: 5, fat: 7, fiber: 1.4, sugar: 3 },
  { name: "Omlet", aliases: ["omelet"], servingSize: 100, servingUnit: "g", calories: 154, protein: 10.6, carbs: 0.6, fat: 12, fiber: 0, sugar: 0.4 },
  { name: "Mercimek Çorbası", aliases: ["mercimek corbasi", "lentil soup"], servingSize: 100, servingUnit: "g", calories: 70, protein: 3.5, carbs: 10, fat: 2, fiber: 2.5, sugar: 1.5 },
  { name: "Ezogelin Çorbası", aliases: ["ezogelin corbasi"], servingSize: 100, servingUnit: "g", calories: 75, protein: 3, carbs: 11, fat: 2.2, fiber: 2.1, sugar: 1.4 },
  { name: "Tarhana Çorbası", aliases: ["tarhana corbasi"], servingSize: 100, servingUnit: "g", calories: 65, protein: 2.5, carbs: 10, fat: 1.8, fiber: 1.5, sugar: 2 },
  { name: "Lahmacun", aliases: ["lahmacun"], servingSize: 100, servingUnit: "g", calories: 250, protein: 10, carbs: 32, fat: 9, fiber: 2, sugar: 2 },
  { name: "Pide", aliases: ["pita", "turkish pide"], servingSize: 100, servingUnit: "g", calories: 275, protein: 11, carbs: 36, fat: 10, fiber: 2, sugar: 2.5 },
  { name: "Pizza", aliases: ["pizza"], servingSize: 100, servingUnit: "g", calories: 266, protein: 11, carbs: 33, fat: 10, fiber: 2.3, sugar: 3.6 },
  { name: "Çiğ Köfte", aliases: ["cig kofte"], servingSize: 100, servingUnit: "g", calories: 180, protein: 4, carbs: 35, fat: 3, fiber: 4, sugar: 2 },
  { name: "Kısır", aliases: ["kisir"], servingSize: 100, servingUnit: "g", calories: 170, protein: 4, carbs: 29, fat: 5, fiber: 4, sugar: 2.5 },
  { name: "Ton Balıklı Salata", aliases: ["ton balikli salata", "tuna salad"], servingSize: 100, servingUnit: "g", calories: 120, protein: 12, carbs: 4, fat: 6, fiber: 1.5, sugar: 1.5 },
  { name: "Tavuklu Salata", aliases: ["chicken salad"], servingSize: 100, servingUnit: "g", calories: 110, protein: 13, carbs: 4, fat: 4.5, fiber: 1.6, sugar: 1.8 },
  { name: "Su", aliases: ["water"], servingSize: 100, servingUnit: "ml", calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0 },
  { name: "Ayran", aliases: ["ayran"], servingSize: 100, servingUnit: "ml", calories: 36, protein: 2, carbs: 2.4, fat: 2, fiber: 0, sugar: 2.4 },
  { name: "Şekersiz Çay", aliases: ["sekersiz cay", "tea"], servingSize: 100, servingUnit: "ml", calories: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0, sugar: 0 },
  { name: "Türk Kahvesi", aliases: ["turk kahvesi", "turkish coffee"], servingSize: 100, servingUnit: "ml", calories: 2, protein: 0.1, carbs: 0, fat: 0, fiber: 0, sugar: 0 },
  { name: "Filtre Kahve", aliases: ["filter coffee"], servingSize: 100, servingUnit: "ml", calories: 2, protein: 0.1, carbs: 0, fat: 0, fiber: 0, sugar: 0 },
  { name: "Kola", aliases: ["cola"], servingSize: 100, servingUnit: "ml", calories: 42, protein: 0, carbs: 10.6, fat: 0, fiber: 0, sugar: 10.6 },
  { name: "Meyve Suyu", aliases: ["fruit juice"], servingSize: 100, servingUnit: "ml", calories: 46, protein: 0.2, carbs: 11, fat: 0.1, fiber: 0.2, sugar: 9.5 },
  { name: "Labne", aliases: ["labneh", "labne peyniri"], servingSize: 100, servingUnit: "g", calories: 220, protein: 7, carbs: 4, fat: 20, fiber: 0, sugar: 3.5 },
  { name: "Krem Peynir", aliases: ["cream cheese"], servingSize: 100, servingUnit: "g", calories: 342, protein: 6, carbs: 4, fat: 34, fiber: 0, sugar: 3.2 },
  { name: "Tulum Peyniri", aliases: ["tulum"], servingSize: 100, servingUnit: "g", calories: 350, protein: 22, carbs: 2, fat: 28, fiber: 0, sugar: 0.5 },
  { name: "Granola", aliases: ["granola"], servingSize: 100, servingUnit: "g", calories: 471, protein: 10, carbs: 64, fat: 20, fiber: 7, sugar: 24 },
  { name: "Müsli", aliases: ["musli", "muesli"], servingSize: 100, servingUnit: "g", calories: 340, protein: 10, carbs: 66, fat: 5, fiber: 8, sugar: 18 },
  { name: "Pekmez", aliases: ["molasses"], servingSize: 100, servingUnit: "g", calories: 290, protein: 0.5, carbs: 75, fat: 0.1, fiber: 0, sugar: 64 },
  { name: "Tahin", aliases: ["tahini"], servingSize: 100, servingUnit: "g", calories: 595, protein: 17, carbs: 21, fat: 53, fiber: 9, sugar: 0.5 },
  { name: "Çavdar Ekmeği", aliases: ["cavdar ekmegi", "rye bread"], servingSize: 100, servingUnit: "g", calories: 259, protein: 8.5, carbs: 48, fat: 3.3, fiber: 5.8, sugar: 3.9 },
  { name: "Simit", aliases: ["simit"], servingSize: 100, servingUnit: "g", calories: 360, protein: 10, carbs: 62, fat: 8, fiber: 3, sugar: 4 },
  { name: "Poğaça", aliases: ["pogaca"], servingSize: 100, servingUnit: "g", calories: 390, protein: 8, carbs: 45, fat: 20, fiber: 2, sugar: 3 },
  { name: "Tavuk Kanat", aliases: ["chicken wings"], servingSize: 100, servingUnit: "g", calories: 203, protein: 30, carbs: 0, fat: 8.1, fiber: 0, sugar: 0 },
  { name: "Dana Bonfile", aliases: ["bonfile", "beef tenderloin"], servingSize: 100, servingUnit: "g", calories: 205, protein: 29, carbs: 0, fat: 9, fiber: 0, sugar: 0 },
  { name: "Dana Antrikot", aliases: ["antrikot", "ribeye"], servingSize: 100, servingUnit: "g", calories: 291, protein: 24, carbs: 0, fat: 22, fiber: 0, sugar: 0 },
  { name: "Kuzu Eti", aliases: ["lamb"], servingSize: 100, servingUnit: "g", calories: 294, protein: 25, carbs: 0, fat: 21, fiber: 0, sugar: 0 },
  { name: "Hamsi", aliases: ["anchovy"], servingSize: 100, servingUnit: "g", calories: 131, protein: 20, carbs: 0, fat: 5, fiber: 0, sugar: 0 },
  { name: "Sardalya", aliases: ["sardine"], servingSize: 100, servingUnit: "g", calories: 208, protein: 25, carbs: 0, fat: 11, fiber: 0, sugar: 0 },
  { name: "Karides", aliases: ["shrimp"], servingSize: 100, servingUnit: "g", calories: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, sugar: 0 },
  { name: "Barbunya", aliases: ["borlotti beans"], servingSize: 100, servingUnit: "g", calories: 127, protein: 8, carbs: 23, fat: 0.5, fiber: 6.4, sugar: 0.3 },
  { name: "Bezelye", aliases: ["peas"], servingSize: 100, servingUnit: "g", calories: 81, protein: 5.4, carbs: 14, fat: 0.4, fiber: 5.7, sugar: 5.7 },
  { name: "Tam Buğday Makarna", aliases: ["tam bugday makarna", "whole wheat pasta"], servingSize: 100, servingUnit: "g", calories: 149, protein: 5.9, carbs: 30, fat: 1.7, fiber: 3.9, sugar: 0.8 },
  { name: "Fırın Patates", aliases: ["firin patates", "baked potato"], servingSize: 100, servingUnit: "g", calories: 93, protein: 2.5, carbs: 21, fat: 0.1, fiber: 2.2, sugar: 1.2 },
  { name: "İrmik", aliases: ["irmik", "semolina"], servingSize: 100, servingUnit: "g", calories: 360, protein: 12.7, carbs: 73, fat: 1.1, fiber: 3.9, sugar: 0.4 },
  { name: "Kuskus", aliases: ["couscous"], servingSize: 100, servingUnit: "g", calories: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, sugar: 0.1 },
  { name: "Kırmızı Soğan", aliases: ["kirmizi sogan", "red onion"], servingSize: 100, servingUnit: "g", calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1, fiber: 1.7, sugar: 4.2 },
  { name: "Patlıcan", aliases: ["patlican", "eggplant"], servingSize: 100, servingUnit: "g", calories: 25, protein: 1, carbs: 5.9, fat: 0.2, fiber: 3, sugar: 3.5 },
  { name: "Pırasa", aliases: ["pirasa", "leek"], servingSize: 100, servingUnit: "g", calories: 61, protein: 1.5, carbs: 14, fat: 0.3, fiber: 1.8, sugar: 3.9 },
  { name: "Enginar", aliases: ["artichoke"], servingSize: 100, servingUnit: "g", calories: 47, protein: 3.3, carbs: 11, fat: 0.2, fiber: 5.4, sugar: 1 },
  { name: "Taze Fasulye", aliases: ["fasulye", "green beans"], servingSize: 100, servingUnit: "g", calories: 31, protein: 1.8, carbs: 7, fat: 0.1, fiber: 3.4, sugar: 3.3 },
  { name: "Semizotu", aliases: ["purslane"], servingSize: 100, servingUnit: "g", calories: 20, protein: 2, carbs: 3.4, fat: 0.4, fiber: 0, sugar: 0 },
  { name: "Maydanoz", aliases: ["parsley"], servingSize: 100, servingUnit: "g", calories: 36, protein: 3, carbs: 6.3, fat: 0.8, fiber: 3.3, sugar: 0.9 },
  { name: "Dereotu", aliases: ["dill"], servingSize: 100, servingUnit: "g", calories: 43, protein: 3.5, carbs: 7, fat: 1.1, fiber: 2.1, sugar: 0 },
  { name: "Nektarin", aliases: ["nectarine"], servingSize: 100, servingUnit: "g", calories: 44, protein: 1.1, carbs: 10.6, fat: 0.3, fiber: 1.7, sugar: 7.9 },
  { name: "Kiraz", aliases: ["cherry"], servingSize: 100, servingUnit: "g", calories: 63, protein: 1.1, carbs: 16, fat: 0.2, fiber: 2.1, sugar: 12.8 },
  { name: "Vişne", aliases: ["visne", "sour cherry"], servingSize: 100, servingUnit: "g", calories: 50, protein: 1, carbs: 12, fat: 0.3, fiber: 1.6, sugar: 8.5 },
  { name: "Ananas", aliases: ["pineapple"], servingSize: 100, servingUnit: "g", calories: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, sugar: 9.9 },
  { name: "Mango", aliases: ["mango"], servingSize: 100, servingUnit: "g", calories: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, sugar: 13.7 },
  { name: "Kivi", aliases: ["kiwi"], servingSize: 100, servingUnit: "g", calories: 61, protein: 1.1, carbs: 14.7, fat: 0.5, fiber: 3, sugar: 9 },
  { name: "Nar", aliases: ["pomegranate"], servingSize: 100, servingUnit: "g", calories: 83, protein: 1.7, carbs: 18.7, fat: 1.2, fiber: 4, sugar: 13.7 },
  { name: "Limon", aliases: ["lemon"], servingSize: 100, servingUnit: "g", calories: 29, protein: 1.1, carbs: 9.3, fat: 0.3, fiber: 2.8, sugar: 2.5 },
  { name: "Kabak Çekirdeği", aliases: ["kabak cekirdegi", "pumpkin seeds"], servingSize: 100, servingUnit: "g", calories: 559, protein: 30, carbs: 10.7, fat: 49, fiber: 6, sugar: 1.4 },
  { name: "Ay Çekirdeği", aliases: ["ay cekirdegi", "sunflower seeds"], servingSize: 100, servingUnit: "g", calories: 584, protein: 21, carbs: 20, fat: 51, fiber: 8.6, sugar: 2.6 },
  { name: "Kuru Kayısı", aliases: ["kuru kayisi", "dried apricot"], servingSize: 100, servingUnit: "g", calories: 241, protein: 3.4, carbs: 63, fat: 0.5, fiber: 7.3, sugar: 53 },
  { name: "Kuru İncir", aliases: ["kuru incir", "dried fig"], servingSize: 100, servingUnit: "g", calories: 249, protein: 3.3, carbs: 64, fat: 0.9, fiber: 9.8, sugar: 48 },
  { name: "Bitter Çikolata", aliases: ["bitter cikolata", "dark chocolate"], servingSize: 100, servingUnit: "g", calories: 598, protein: 7.8, carbs: 45.9, fat: 42.6, fiber: 10.9, sugar: 24 },
  { name: "Sütlü Çikolata", aliases: ["sutlu cikolata", "milk chocolate"], servingSize: 100, servingUnit: "g", calories: 535, protein: 7.7, carbs: 59, fat: 30, fiber: 3.4, sugar: 52 },
  { name: "Tavuk Şiş", aliases: ["tavuk sis", "chicken skewer"], servingSize: 100, servingUnit: "g", calories: 180, protein: 27, carbs: 2, fat: 7, fiber: 0.2, sugar: 0.5 },
  { name: "Adana Kebap", aliases: ["adana kebab"], servingSize: 100, servingUnit: "g", calories: 250, protein: 17, carbs: 2, fat: 20, fiber: 0.3, sugar: 0.5 },
  { name: "Urfa Kebap", aliases: ["urfa kebab"], servingSize: 100, servingUnit: "g", calories: 245, protein: 17, carbs: 2, fat: 19, fiber: 0.3, sugar: 0.5 },
  { name: "Etli Ekmek", aliases: ["etli ekmek"], servingSize: 100, servingUnit: "g", calories: 240, protein: 11, carbs: 34, fat: 7, fiber: 2, sugar: 2 },
  { name: "Yayla Çorbası", aliases: ["yayla corbasi"], servingSize: 100, servingUnit: "g", calories: 65, protein: 2.5, carbs: 8, fat: 2.5, fiber: 0.4, sugar: 2.5 },
  { name: "Domates Çorbası", aliases: ["domates corbasi", "tomato soup"], servingSize: 100, servingUnit: "g", calories: 45, protein: 1.2, carbs: 7, fat: 1.5, fiber: 1.2, sugar: 4 },
  { name: "Çoban Salata", aliases: ["coban salata"], servingSize: 100, servingUnit: "g", calories: 45, protein: 1.2, carbs: 5, fat: 2.5, fiber: 1.6, sugar: 2.8 },
  { name: "Sezar Salata", aliases: ["caesar salad"], servingSize: 100, servingUnit: "g", calories: 180, protein: 8, carbs: 7, fat: 14, fiber: 2, sugar: 2 },
  { name: "Mantı", aliases: ["manti"], servingSize: 100, servingUnit: "g", calories: 220, protein: 9, carbs: 30, fat: 7, fiber: 1.5, sugar: 2 },
  { name: "Sarma", aliases: ["yaprak sarma"], servingSize: 100, servingUnit: "g", calories: 160, protein: 3, carbs: 22, fat: 7, fiber: 3, sugar: 2 },
  { name: "Dolma", aliases: ["stuffed pepper"], servingSize: 100, servingUnit: "g", calories: 150, protein: 4, carbs: 20, fat: 6, fiber: 3, sugar: 3 },
  { name: "İmam Bayıldı", aliases: ["imam bayildi"], servingSize: 100, servingUnit: "g", calories: 145, protein: 2, carbs: 10, fat: 11, fiber: 3.5, sugar: 4 },
  { name: "Karnıyarık", aliases: ["karniyarik"], servingSize: 100, servingUnit: "g", calories: 170, protein: 7, carbs: 9, fat: 12, fiber: 3, sugar: 4 },
  { name: "Kuru Fasulye Yemeği", aliases: ["kuru fasulye yemegi"], servingSize: 100, servingUnit: "g", calories: 155, protein: 7, carbs: 22, fat: 4, fiber: 6, sugar: 1.5 },
  { name: "Nohut Yemeği", aliases: ["nohut yemegi"], servingSize: 100, servingUnit: "g", calories: 165, protein: 7, carbs: 23, fat: 5, fiber: 6, sugar: 2 },
  { name: "Sebzeli Türlü", aliases: ["sebzeli turlu"], servingSize: 100, servingUnit: "g", calories: 80, protein: 2, carbs: 11, fat: 3, fiber: 3, sugar: 4 },
  { name: "Laktozsuz Süt", aliases: ["laktozsuz sut", "lactose free milk"], servingSize: 100, servingUnit: "ml", calories: 45, protein: 3.2, carbs: 4.8, fat: 1.5, fiber: 0, sugar: 4.8 },
  { name: "Süzme Yoğurt", aliases: ["suzme yogurt", "greek yogurt"], servingSize: 100, servingUnit: "g", calories: 95, protein: 9, carbs: 3.6, fat: 5, fiber: 0, sugar: 3.6 },
  { name: "Kefir", aliases: ["kefir"], servingSize: 100, servingUnit: "ml", calories: 55, protein: 3.5, carbs: 4.5, fat: 2.5, fiber: 0, sugar: 4.5 },
  { name: "Protein Shake", aliases: ["protein icecegi"], servingSize: 100, servingUnit: "ml", calories: 70, protein: 10, carbs: 4, fat: 1.5, fiber: 0, sugar: 3 },
  { name: "Espresso", aliases: ["espresso"], servingSize: 100, servingUnit: "ml", calories: 2, protein: 0.1, carbs: 0, fat: 0, fiber: 0, sugar: 0 },
  { name: "Latte", aliases: ["caffe latte"], servingSize: 100, servingUnit: "ml", calories: 45, protein: 2.3, carbs: 4.2, fat: 2.2, fiber: 0, sugar: 4.2 },
  { name: "Şekersiz Kola", aliases: ["sekersiz kola", "zero cola"], servingSize: 100, servingUnit: "ml", calories: 1, protein: 0, carbs: 0.1, fat: 0, fiber: 0, sugar: 0 },
  { name: "Portakal Suyu", aliases: ["orange juice"], servingSize: 100, servingUnit: "ml", calories: 45, protein: 0.7, carbs: 10.4, fat: 0.2, fiber: 0.2, sugar: 8.4 },
  { name: "Whey Protein", aliases: ["protein tozu", "whey"], servingSize: 100, servingUnit: "g", calories: 400, protein: 80, carbs: 8, fat: 6, fiber: 0, sugar: 5 },
  { name: "Kreatin", aliases: ["creatine"], servingSize: 100, servingUnit: "g", calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0 },
  { name: "Protein Bar", aliases: ["protein bar"], servingSize: 100, servingUnit: "g", calories: 360, protein: 30, carbs: 35, fat: 12, fiber: 8, sugar: 8 },
  { name: "Pirinç Patlağı", aliases: ["pirinc patlagi", "rice cake"], servingSize: 100, servingUnit: "g", calories: 387, protein: 8, carbs: 82, fat: 3, fiber: 4, sugar: 0.5 },
  { name: "Yulaf Ezmesi", aliases: ["oatmeal"], servingSize: 100, servingUnit: "g", calories: 68, protein: 2.4, carbs: 12, fat: 1.4, fiber: 1.7, sugar: 0.5 },
  { name: "Light Yoğurt", aliases: ["light yogurt"], servingSize: 100, servingUnit: "g", calories: 45, protein: 4, carbs: 5, fat: 1, fiber: 0, sugar: 5 },
  { name: "Light Süt", aliases: ["light sut", "low fat milk"], servingSize: 100, servingUnit: "ml", calories: 42, protein: 3.4, carbs: 5, fat: 1, fiber: 0, sugar: 5 },
  { name: "Light Peynir", aliases: ["light cheese"], servingSize: 100, servingUnit: "g", calories: 180, protein: 20, carbs: 4, fat: 9, fiber: 0, sugar: 1 },
  { name: "Hindi Füme", aliases: ["hindi fume", "turkey slices"], servingSize: 100, servingUnit: "g", calories: 110, protein: 20, carbs: 2, fat: 2, fiber: 0, sugar: 1 },
  { name: "Sucuk", aliases: ["sucuk"], servingSize: 100, servingUnit: "g", calories: 450, protein: 24, carbs: 2, fat: 38, fiber: 0, sugar: 1 },
  { name: "Pastırma", aliases: ["pastirma"], servingSize: 100, servingUnit: "g", calories: 250, protein: 30, carbs: 1, fat: 14, fiber: 0, sugar: 0.5 },
  { name: "Fırın Tavuk", aliases: ["firin tavuk", "roast chicken"], servingSize: 100, servingUnit: "g", calories: 190, protein: 28, carbs: 0, fat: 8, fiber: 0, sugar: 0 },
  { name: "Börek", aliases: ["borek"], servingSize: 100, servingUnit: "g", calories: 330, protein: 9, carbs: 35, fat: 17, fiber: 2, sugar: 2 },
  { name: "Gözleme", aliases: ["gozleme"], servingSize: 100, servingUnit: "g", calories: 290, protein: 9, carbs: 38, fat: 11, fiber: 2, sugar: 2 },
  { name: "Cacık", aliases: ["cacik"], servingSize: 100, servingUnit: "g", calories: 45, protein: 2.5, carbs: 3.5, fat: 2.5, fiber: 0.4, sugar: 3 },
  { name: "Humus", aliases: ["hummus"], servingSize: 100, servingUnit: "g", calories: 166, protein: 7.9, carbs: 14.3, fat: 9.6, fiber: 6, sugar: 0.3 },
  { name: "Falafel", aliases: ["falafel"], servingSize: 100, servingUnit: "g", calories: 333, protein: 13.3, carbs: 31.8, fat: 17.8, fiber: 4.9, sugar: 0 },
  { name: "Zeytinyağı", aliases: ["zeytinyagi", "olive oil"], servingSize: 100, servingUnit: "g", calories: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0 },
  { name: "Avokadolu Tost", aliases: ["avocado toast"], servingSize: 100, servingUnit: "g", calories: 210, protein: 6, carbs: 24, fat: 10, fiber: 5, sugar: 2 },
  { name: "Tavuklu Sandviç", aliases: ["tavuklu sandvic", "chicken sandwich"], servingSize: 100, servingUnit: "g", calories: 220, protein: 14, carbs: 25, fat: 7, fiber: 2, sugar: 3 },
  { name: "Ton Balıklı Sandviç", aliases: ["ton balikli sandvic", "tuna sandwich"], servingSize: 100, servingUnit: "g", calories: 230, protein: 14, carbs: 24, fat: 9, fiber: 2, sugar: 2.5 },
  { name: "Sebzeli Omlet", aliases: ["vegetable omelet"], servingSize: 100, servingUnit: "g", calories: 130, protein: 9, carbs: 4, fat: 9, fiber: 1, sugar: 2 },
  { name: "Yulaflı Pankek", aliases: ["yulafli pankek", "oat pancake"], servingSize: 100, servingUnit: "g", calories: 190, protein: 8, carbs: 27, fat: 6, fiber: 3, sugar: 5 },
  { name: "Balık", aliases: ["balik", "fish"], servingSize: 100, servingUnit: "g", calories: 130, protein: 22, carbs: 0, fat: 4, fiber: 0, sugar: 0 }
];
